server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 100MB
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource #数据源类型：hikaricp
    url: jdbc:mysql://localhost:3306/db_soft1921?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true