spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_soft1921?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.inky.boot.mybatis.domain
  configuration:
    map-underscore-to-camel-case: true
